In [1]:
import numpy as np

### np.arrange

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,3)

array([1, 4, 7])

### np.ones, np.zeros

In [5]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### np.empty , np.full

In [9]:
np.empty((3,4))

array([[ 1.49166815e-154, -2.00000015e+000,  3.95252517e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  1.49166815e-154,
         1.49166815e-154],
       [ 2.47032823e-323,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000]])

In [10]:
np.full((2,3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

### np.eye : 단위행렬

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.linspace

In [13]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

### reshape 함수 : ndarray의 형태, 차원을 바꾸기 위해 사용

In [29]:
x = np.arange(1, 16)
print(x)

x.shape

x.reshape(5, 3, 1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

### random
### rand 함수 : 0, 1 사이의 분포로 랜덤한 ndarray 생성

In [32]:
np.random.rand(2,3)

array([[0.78277971, 0.85325885, 0.07257691],
       [0.43711126, 0.23510457, 0.01676231]])

### randn 함수
#### n : normal distribution (정규분포)
#### 정규분포로 샘플링 된 랜덤 ndarray 생성

In [33]:
np.random.randn(3,4)

array([[ 0.38627206, -1.43478786,  1.37179484, -1.24895081],
       [ 0.64826187,  0.74949439, -0.5905644 , -0.21752913],
       [-0.76650051,  0.83696933,  0.23381552, -0.15016523]])

### randint 함수 : 특정 함수 사이에서 랜덤하게 샘플링

In [39]:
np.random.randint(1, 100, size=(3,5))

array([[80, 25, 84,  1, 16],
       [69, 52, 90, 57, 23],
       [89, 46, 57, 85, 32]])

### Seed 함수 : 랜덤한 값을 동일하게 다시 생성하고자 할 때 사용

In [41]:
np.random.seed(88)
np.random.randn(3, 5)

array([[ 0.1068843 ,  2.20581524,  0.95656269,  0.0684111 ,  1.06851382],
       [ 0.99718264, -0.93154792,  0.73043049, -0.17121369, -1.28869118],
       [ 1.06143594, -0.04050128, -0.90372141, -1.55413303, -0.95113284]])

### Choice : 주어진 1차원 ndarray로부터 랜덤으로 샘플링. 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [44]:
np.random.choice(100, size=(3,4))

array([[21,  3, 94, 89],
       [13, 47, 67, 46],
       [23, 77, 51, 41]])

In [48]:
x = np.array([1, 3, 2.5, 6, 7, 4.9])
np.random.choice(x, size=(2,3), replace=False) #replace = False : 중복 불가능

array([[1. , 6. , 4.9],
       [3. , 7. , 2.5]])

### 인덱싱
#### 파이썬 리스트와 동일한 개념으로 사용
#### ,를 사용하여 각 차원의 인덱스에 접근 가능

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
x[3] = 100
print(x)

[  0   1   2 100   4   5   6   7   8   9]


In [7]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
x[0]

array([0, 1, 2, 3, 4])

In [9]:
x[0, 3]

3

In [12]:
x = np.arange(36).reshape(3,4,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [13]:
x[1,2,1]

19

### 슬라이싱

In [15]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
x[:, 1:4] #x[행, 열]

array([[1, 2, 3],
       [6, 7, 8]])

In [19]:
x[0, :2] #벡터

array([0, 1])

In [20]:
x[:1, :2] #행렬 2차원으로 출력됨 / ':'를 쓰면 차원유지

array([[0, 1]])

In [22]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [26]:
x[:1, 1:3, :2]

array([[[3, 4],
        [6, 7]]])

### ravel : 다차원 배열을 1차원으로 변경

In [27]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
x.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.ravel(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### flatten
- 다차원 배열을 1차원으로 변경
- ravel과의 차이점 : 복사본을 생성하여 변경함(원본 데이터가 아닌 복사본을 반환)
- order 파라미터 : C - row 우선 변경 , F - column 우선 변경

In [30]:
temp = x.ravel()
print(temp)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
temp[0] = 100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9]
[[100   1   2   3   4]
 [  5   6   7   8   9]]


In [33]:
y = np.arange(10).reshape(5,2)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [34]:
y.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
t2 = y.flatten(order='F')
print(t2)

[0 2 4 6 8 1 3 5 7 9]


In [37]:
t2[0] = 100
print(t2)
print(y)

[100   1   2   3   4   5   6   7   8   9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [41]:
np.arange(36).reshape(3, -1) # -1을 사용하면 총 숫자에 맞게 행 또는 열을 알아서 계산하라는 의미

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

### 연산함수
- add, substract, multiply, divide

In [44]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.29946869 0.46013374 0.22525039 0.26710021 0.17611435]
 [0.84853672 0.93233682 0.07146119 0.91139455 0.40527596]
 [0.02723219 0.43619697 0.66694387 0.11335333 0.78072784]]


In [45]:
np.add(x, y) #shape이 같아야 가능

array([[ 0.29946869,  1.46013374,  2.22525039,  3.26710021,  4.17611435],
       [ 5.84853672,  6.93233682,  7.07146119,  8.91139455,  9.40527596],
       [10.02723219, 11.43619697, 12.66694387, 13.11335333, 14.78072784]])

In [46]:
np.subtract(x, y) # 뺄셈

array([[-0.29946869,  0.53986626,  1.77474961,  2.73289979,  3.82388565],
       [ 4.15146328,  5.06766318,  6.92853881,  7.08860545,  8.59472404],
       [ 9.97276781, 10.56380303, 11.33305613, 12.88664667, 13.21927216]])

In [48]:
np.divide(x, y) #나눗셈

array([[  0.        ,   2.1732812 ,   8.87900777,  11.23173964,
         22.71251598],
       [  5.89249693,   6.43544253,  97.95526938,   8.7777571 ,
         22.20709062],
       [367.212508  ,  25.2179653 ,  17.99251854, 114.68564247,
         17.93198516]])

In [49]:
x + y

array([[ 0.29946869,  1.46013374,  2.22525039,  3.26710021,  4.17611435],
       [ 5.84853672,  6.93233682,  7.07146119,  8.91139455,  9.40527596],
       [10.02723219, 11.43619697, 12.66694387, 13.11335333, 14.78072784]])

### 통계함수
- 평균, 분산, 중앙, 최대, 최소값 등 통계 관련된 함수 내장

In [50]:
print(y)

[[0.29946869 0.46013374 0.22525039 0.26710021 0.17611435]
 [0.84853672 0.93233682 0.07146119 0.91139455 0.40527596]
 [0.02723219 0.43619697 0.66694387 0.11335333 0.78072784]]


In [51]:
np.mean(y) #평균

0.44143512127350015

In [52]:
y.mean()

0.44143512127350015

In [53]:
np.max(y)

0.9323368168207471

In [55]:
np.argmax(y) #가장 큰값의 인덱스 값

6

In [57]:
np.var(y), np.median(y), np.std(y) #분산, median, 표준편차

(0.09193312492455231, 0.40527596138410726, 0.30320475742400926)

### 집계함수 

In [63]:
np.sum(y, axis=1)

array([1.42806738, 3.16900524, 2.0244542 ])

In [60]:
np.cumsum(y) #누적합계

array([0.29946869, 0.75960243, 0.98485282, 1.25195303, 1.42806738,
       2.2766041 , 3.20894092, 3.2804021 , 4.19179666, 4.59707262,
       4.62430481, 5.06050177, 5.72744565, 5.84079898, 6.62152682])

### any, all 함수
- any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
- all : 모든 원소가 특정 조건을 만족하면 True, 아니면 False

In [64]:
z = np.random.randn(10).reshape(2, -1)
print(z)

[[ 1.03372526  0.13183565 -0.61794138 -0.51483176  0.18123549]
 [-0.77897049  0.2925877   0.10446064 -1.82125696  0.74670029]]


In [65]:
np.any(z > 0)

True

In [66]:
np.all(z > 0)

False

### Wherer 함수
- 조건에 따라 선별적으로 값을 선택 가능
- 예) 음수인 경우는 0, 나머지는 값을 그대로 쓸 때

In [67]:
z = np.random.randn(10)
print(z)

[-0.91374519 -0.77350621 -0.40849144  0.89584423 -1.30088408  1.00066041
  0.14076752  0.06362311 -1.32020689  0.82084107]


In [68]:
np.where(z > 0, z, 0)

array([0.        , 0.        , 0.        , 0.89584423, 0.        ,
       1.00066041, 0.14076752, 0.06362311, 0.        , 0.82084107])

### axis

In [70]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [71]:
np.sum(z, axis=0)

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [72]:
np.sum(z, axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [73]:
np.sum(z, axis=2)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [76]:
np.sum(z, axis=(1,2))

array([ 66, 210, 354])