In [1]:
import numpy as np

### np.arrange

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,3)

array([1, 4, 7])

### np.ones, np.zeros

In [5]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### np.empty , np.full

In [9]:
np.empty((3,4))

array([[ 1.49166815e-154, -2.00000015e+000,  3.95252517e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  1.49166815e-154,
         1.49166815e-154],
       [ 2.47032823e-323,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000]])

In [10]:
np.full((2,3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

### np.eye : 단위행렬

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.linspace

In [13]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

### reshape 함수 : ndarray의 형태, 차원을 바꾸기 위해 사용

In [29]:
x = np.arange(1, 16)
print(x)

x.shape

x.reshape(5, 3, 1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])