In [4]:
!pip install numpy

In [3]:
#관례적으로 np라는 약자를 많이 사용
import numpy as np

In [5]:
a = np.array([0, 1, 2, 3, 4, 5])*2
a

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [7]:
np.linspace(0, 100 ,100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [8]:
np.array(11)

array(11)

In [9]:
a1d = np.array([1,2,3])

In [11]:
a1d.dtype

dtype('int64')

In [13]:
b1d = np.array([[1,2,3], [4,5,6]])

In [15]:
b1d.shape

(2, 3)

In [22]:
d1d = np.random.random((2,2))

In [20]:
d1d

array([[0.07930133, 0.35221731],
       [0.20846703, 0.72711537]])